project:
  type: website

website:
  title: "Juan Felipe Escobar"
  navbar:
    left:
      - href: index.html
        text: Home
      - href: experience.html
        text: Experience
      - href: education.html
        text: Education
      - href: references.html
        text: References
      - href: skills.html
        text: Skills
      - href: contact.html
        text: Contact
      - href: leadership.html
        text: Leadership
      - href: projects.html
        text: Projects
      
    right:
      - href: "Juan-Escobar-Resume.pdf"
        text: Resume
      - href: https://www.linkedin.com/
        text: LinkedIn
format:
  html:
    theme: darkly
    toc: false
    smooth-scroll: true
    css: styles.css




